[tool.poetry]
name = "example-flink-job"
version = "0.1.0"
description = ""
authors = ["Matt Camp <matt@aiexcalibur.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
quixstreams = "^2.4.2"

[tool.poetry.group.dev.dependencies]
pytest-mock = "^3.14.0"
pytest = "^8.1.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
