[tool.poetry]
name = "excalibur-nvim"
version = "0.1.0"
description = ""
authors = ["Matt Camp <matt@aiexcalibur.com>"]
readme = "README.md"
packages = [{include = "excalibur_nvim"}]

[tool.poetry.dependencies]
python = ">=3.10,<3.13"  # Adjusted line
kaleido = "0.2.1"
jupyter-core = "^5.5.0"
pynvim = "^0.4.3"
jupyter-client = "^8.5.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
