# https://numtide.github.io/devshell
[devshell]
packages = [
  "julia",
  "git",
  "gitRepo",
  "gnupg",
  "autoconf",
  "curl",
  "procps",
  "gnumake",
  "util-linux",
  "m4",
  "gperf",
  "unzip",
  # "cudatoolkit",
  "linuxPackages.nvidia_x11",
  "libGLU",
  "libGL",
  "xorg.libXi",
  "xorg.libXmu",
  "freeglut",
  "xorg.libXext",
  "xorg.libX11",
  "xorg.libXv", 
  "xorg.libXrandr",
  "zlib",
  "ncurses5", 
  "stdenv.cc",
  "binutils",
  "cudaPackages.cudnn",
  "cudaPackages.nvidia_fs",
  "cudaPackages.cutensor",
  "cudaPackages.cuda_nvml_dev"
]
